{
    'name': 'Tata Usaha Sekolah',
    'version': '12.0.1.0.0',
    'summary': """Tata Usaha Sekolah""",
    'description': 'This module is manage finance school',
    "category": "Education",
    'author': 'Muhammad Azis - 087881071515',
    'company': 'Ismata Nusantara Abadi',
    'website': "https://www.ismata.co.id",
    'depends': ['base', 'base_sekolah', 'account', 'account_voucher', 'account_cancel', 'sale'],
    'data': [
        'report/report_manifest_pembayaran.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'wizard/wizard_view.xml',
        'views/invoice_view.xml',
        'views/partner_view.xml',
        'views/tatausaha_view.xml',
    ],
    'images': [],
    'license': 'AGPL-3',
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
