{
    'name': 'Siap BK',
    'version': '12.0.1.0.0',
    'summary': """Keperluan Untuk BK""",
    'description': 'Ini merupakan module Siap BK',
    "category": "BK",
    'author': 'RizkyAbdiSyahputraHasibuan-085175257741',
    'company': 'PT LINTANG UTAMA INFOTEK',
    'website': "https://lui.co.id/",
    'depends': ['base', 'base_sekolah',],
    'data': [
        # 'security/security.xml',
        'views/kegiatan_tambahan_view.xml',
        'views/layanan_individu_view.xml',
        'views/layanan_media_view.xml',
        'views/bimbingan_kelompok_view.xml',
        'views/bimbingan_klasikal_view.xml',
        'views/bimbingan_lintas_view.xml',
        'views/konseling_kelompok_view.xml',
        'views/konsultasi_view.xml',
        'views/kolaborasi_view.xml',
        'views/alih_tangan_view.xml',
        'views/kunjungan_rumah_view.xml',
        'views/layanan_advokasi_view.xml',
        'views/konverensi_kasus_view.xml',
        'views/menu.xml',  
        'security/ir.model.access.csv',
    ],
    'images': [],
    'license': 'AGPL-3',
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
